// pages/about/mission-vision.tsx
import { Layout } from '../../components/util/Layout'

const MissionVision = () => {
  return (
    <Layout title="FCC | Mission & Vision">
      <main className="flex min-h-[80vh] items-start justify-center">
        <section className="container flex flex-col items-center h-full mt-[12rem] px-4 sm:px-6">
          <h1 className="text-5xl font-bold self-start">Mission and Vision</h1>
        </section>
      </main>
    </Layout>
  )
}

export default MissionVision

// src/routes/about/mission-vision/+page.svelte
<script>
	import { Stepper, Step } from '@skeletonlabs/skeleton'
</script>

<svelte:head>
	<title>FCC | Mission & Vision</title>
</svelte:head>

<section class="container mx-auto flex flex-col h-screen">
	<h1 class="flex justify-center">mission vision page</h1>
	<Stepper>
		<Step>
			<svelte:fragment slot="header">(header)</svelte:fragment>
			(content)
		</Step>
		<Step>
			<svelte:fragment slot="header">(header)</svelte:fragment>
			(content)
		</Step>
	</Stepper>
</section>
