// components/home/Hero.tsx
import Link from 'next/link'

export default function Hero() {
  return (
    <section className="flex flex-col min-h-[40rem] align-center justify-center">
      <h1 className="text-5xl">Welcome to Freedom in Christ Church.</h1>
      <div className="flex justify-center align-middle gap-2 my-10 text-white">
        <Link
          className="px-6 py-3 bg-blue rounded-md ease-in hover:opacity-90"
          href="/about">
          I'm new
        </Link>
        <Link
          className="px-6 py-3 bg-blue rounded-md ease-in hover:opacity-90"
          href="sermons">
          Sermons
        </Link>
      </div>
    </section>
  )
}

// apps/web/src/lib/components/home/Hero.svelte
<section class="bg-hero h-[80vh] bg-cover bg-center bg-no-repeat px-4">
	<div
		class="container mx-auto flex h-full flex-col items-center justify-center"
	>
		<h1 class="h1 z-10 text-center text-5xl font-bold text-white">
			Welcome to Freedom in Christ Church.
		</h1>
		<h2 class="h2 my-8 text-center text-2xl text-white md:w-[50rem]">
			A Christ-centred, Holy Spirit-led community committed to the building of
			strong relationships and planting of healthy reproducing churches.
		</h2>
		<div class="my-8 flex gap-8">
			<a
				href="/about"
				class="variant-filled btn-xl btn"
				data-sveltekit-preload-data="hover">I'm new</a
			>
			<a
				href="/sermons"
				class="variant-filled btn-xl btn"
				data-sveltekit-preload-data="hover">Sermons</a
			>
		</div>
	</div>
</section>
