// pages/about/mission-vision.tsx
import { Layout } from '../../components/util/Layout'

const MissionVision = () => {
  return (
    <Layout title="FCC | Mission & Vision">
      <main className="flex min-h-[80vh] items-start justify-center">
        <section className="container flex flex-col items-center h-full mt-[12rem] px-4 sm:px-6">
          <h1 className="text-5xl font-bold self-start">Mission and Vision</h1>
        </section>
      </main>
    </Layout>
  )
}

export default MissionVision

// apps/web/src/routes/about/mission-vision/+page.svelte
<script lang="ts">
	import FccLayout from '$lib/components/FccLayout.svelte'

	export let data

	const title = data.title
	const breadcrumb = data.breadcrumb
	const headData = data.headData
	const missionVision = data.missionVision
</script>

<FccLayout {title} {breadcrumb} {headData}>
	<div class="grid gap-4 md:grid-cols-2">
		<!-- mission -->
		<div class="flex flex-col items-start justify-start gap-6">
			<h2 class="h2 font-bold">Our Mission:</h2>
			<h3 class="h3">{missionVision.mission}</h3>
		</div>
		<!-- vision -->
		<div class="flex flex-col items-start justify-start gap-6">
			<h2 class="h2 font-bold">Our Vision:</h2>
			<h3 class="h3">{missionVision.vision}</h3>
		</div>
	</div>
</FccLayout>
