// pages/smallgroups/university-bible-study.tsx
import { Layout } from '../../components/util/Layout'

const UniversityBibleStudy = () => {
  return (
    <Layout title="FCC | University Bible Study">
      <section>
        <h1 className="text-5xl">University Bible Study</h1>
      </section>
    </Layout>
  )
}

export default UniversityBibleStudy

// src/routes/small-groups/university-bible-study/+page.svelte
<script lang="ts">
	import FccLayout from '$lib/components/FccLayout.svelte'
	import PageTitle from '$lib/components/PageTitle.svelte'

	const breadcrumb = [
		{ title: 'Home', href: '/' },
		{ title: 'Small Groups', href: '/small-groups' },
		{ title: 'University Bible Study', href: '/university-bible-study' },
	]
</script>

<FccLayout {breadcrumb} title="FCC | University Bible Study">
	<PageTitle text="FCC University Bible Study." />
</FccLayout>
