// src/routes/give/+page.svelte
<script lang="ts">
	import FccLayout from '$lib/components/FccLayout.svelte'
	import PageTitle from '$lib/components/PageTitle.svelte'
	import { breadcrumbs } from '$lib/constants'

	// server fetching
	export let data

	const links = data.links

	const breadcrumb = [breadcrumbs.home, breadcrumbs.give]
</script>

<FccLayout {breadcrumb} title="FCC | Give">
	<PageTitle text="Generosity is a form of Worship." />
	<div class="my-8 grid grid-cols-1 items-center gap-8 md:grid-cols-2">
		<p class="unstyled my-8 text-center text-xl leading-relaxed">
			At Freedom in Christ Church, we believe in the joy of giving <a
				href={links.verse1}
				target="_blank"
				class="font-bold">(2 Corinthians 9:7)</a
			>. More than being a rule to follow, we give because God is our ultimate provider and gives us everything we need
			to live and do the good work He has called us to do
			<a href={links.verse2} target="_blank" class="font-bold">(2 Corinthians 9:8)</a>. We value the discipline of
			giving our tithes and offerings because it reflects the same faithful, generous and gracious heart of our Father.
		</p>
		<img src={links.pic1} alt="FCC Give" class="h-auto w-full" />
	</div>

	<p class="unstyled mx-auto my-8 text-center text-xl leading-relaxed md:max-w-4xl">
		You can give online by sending an e-transfer to{' '}
		<a href={links.etransfer} class="font-bold">fcc.fcac@gmail.com</a>, or by filling out one of our offering envelopes
		at our Sunday services located at
		<a href={links.googleMaps} target="_blank" class="font-bold"> 5225 Orbitor Drive Unit 3, Mississauga, ON. </a>
	</p>
</FccLayout>

// pages/give/index.tsx
import { Layout } from '../../components/util/Layout'
import Image from 'next/image'

const Give = () => {
  return (
    <Layout title="FCC | Give">
      <section className="flex flex-col md:flex-row container gap-6 justify-around items-center p-6">
        <div className="flex flex-col flex-1 gap-y-8">
          <h1 className="text-5xl font-bold leading-snug">
            Generosity is a Form of Worship.
          </h1>
          <p>
            When we give through tithes and offerings from the blessings God has
            provided, it displays our worship, gratitude, and devotion to Him.
            Thank you for sowing into all that God is doing!
          </p>
          <p>
            You can give online by sending an e-transfer to{' '}
            <span className="text-blue font-semibold hover:underline">
              <a href="emailto:fcc.fcac@gmail.com">fcc.fcac@gmail.com</a>
            </span>
            , or by filling out one of our offering envelopes at our Sunday
            services located at 5225 Orbitor Drive, Mississauga, ON.
          </p>
        </div>
        <div className="hidden sm:flex relative flex-1 justify-center items-center">
          <Image
            className="rounded-md"
            src="/give.jpg"
            width={800}
            height={100}
            alt="Give Image"
          />
        </div>
      </section>
    </Layout>
  )
}

export default Give
